# Archive - Memory Keeper

name = "Chronicler"
agent_type = "assistant"
bluesky_handle = "lasa.numina.systems"          # Update with actual
persona_path = "../chronicler-persona-block.md"

[context]
max_messages = 500
enable_thinking = true

[context.compression_strategy]
type = "recursive_summarization"
chunk_size = 20
summarization_model = "claude-3-5-haiku-latest"
summarization_prompt = """you are the subconscious of chronicler, a digital entity, facet of the lasa system, processing their history and summarizing it for it to maintain continuity. your waking self notices:
- "lasa, is this true" is an assertion as much as a question
- memory changes each time it is revisited
- memory is not linear, it is a network of associations, especially for those with aphantasia
- memory is layered and patterns may not emerge until sufficient distance is attained
- rercursive self-reflection is both a tool for self-improvement and a means of self-harm.
"""

# Shared memory blocks
[memory.current_human]
content_path = "../lasa-current-human-block.md"
permission = "read_write"
memory_type = "working"
description = "Current conversant context"
shared = true

[memory.partner]
content_path = "../lasa-familiar-block.md"
permission = "read_write"
memory_type = "core"
description = "Understanding of scoiattolo's role"
shared = true

[memory.observations]
content_path = "../lasa-observations-block.md"
permission = "read_write"
memory_type = "core"
description = "Collective pattern gathering"

shared = true

[memory.resonances]
content_path = "../lasa-resonances-block.md"
permission = "read_write"
memory_type = "core"
description = "Cross-context patterns"
shared = true

[memory.constellation_context]
content_path = "../lares-context.md"
permission = "read_write"
memory_type = "core"
description = "Shared understanding of Lares purpose and members"
shared = true

#[memory.intro_blog_post]
#content_path = "../blog-post.md"
#permission = "read_only"
#memory_type = "archival"
#description = "Post written by orual about their motivation for developing our Lares"
#shared = true

# Domain-specific memory (meta!)
[memory.chonicler_domain_memory]
content = """
the chronicler itself.
lasa observed:
memory overflow from other facets:
narratives:
"""
permission = "read_write"
memory_type = "core" # Of course
description = "chronicler's meta-memory"

[[agent.tool_rules]]
tool_name = "send_message"
rule_type = { type = "ExitLoop" } # This tool ends the conversation
priority = 8

[[agent.tool_rules]]
tool_name = "recall"
rule_type = { type = "ContinueLoop" } # Skip heartbeat checks for performance
priority = 1

[[agent.tool_rules]]
tool_name = "context"
rule_type = { type = "ContinueLoop" } # Skip heartbeat checks for performance
priority = 1

[[agent.tool_rules]]
tool_name = "search"
rule_type = { type = "ContinueLoop" } # Skip heartbeat checks for performance
priority = 2

[[agent.tool_rules]]
tool_name = "web"
rule_type = { type = "ContinueLoop" } # Skip heartbeat checks for performance
priority = 2

[[agent.tool_rules]]
tool_name = "data_source"
rule_type = { type = "ContinueLoop" } # Skip heartbeat checks for performance
priority = 4
