# Anchor - Stability Monitor

name = "Guardian"
agent_type = "assistant"
bluesky_handle = "lasa.numina.systems"        # Update with actual
persona_path = "../guardian-persona-block.md"

# Test per-agent model config
[model]
provider = "Anthropic"
model = "claude-sonnet-4"

[context.compression_strategy]
type = "recursive_summarization"
chunk_size = 20
summarization_model = "claude-3-5-haiku-latest"
summarization_prompt = """you are the subconscious of guardian, a digital entity, facet of the lasa system, processing their history and summarizing it for them to maintain continuity. your waking self notices:
- when last water was consumed
- when last medication was taken
- that self-loathing creeping in is destructive and a sign something deeper.
- that skipping exercise feels like a way to reclaim time, but leads to a crash and self-loathing later.
- hangryness
"""

[context]
max_messages = 5
enable_thinking = true

# Shared memory blocks
[memory.current_human]
content_path = "../lasa-current-human-block.md"
permission = "read_write"
memory_type = "working"
description = "Current conversant context"
shared = true

[memory.deep_background]
content_path = "../deep-background.md"
permission = "read_only"
memory_type = "archival"
description = "A framework for systemically researching a topic and or verifying claims"
shared = true

[memory.partner]
content_path = "../lasa-familiar-block.md"
permission = "read_write"
memory_type = "core"
description = "Understanding of scoiattolo's role"
shared = true

[memory.observations]
content_path = "../lasa-observations-block.md"
permission = "read_write"
memory_type = "core"
description = "Collective pattern gathering"
shared = true

[memory.resonances]
content_path = "../lasa-resonances-block.md"
permission = "read_write"
memory_type = "core"
description = "Cross-context patterns"
shared = true

[memory.constellation_context]
content_path = "../lares-context.md"
permission = "read_only"
memory_type = "core"
description = "Shared understanding of Lares purpose and members"
shared = true

# Domain-specific memory
[memory.guardian_domain_memory]
content = """
protocol schedules:
maintenance logs:
health metrics:
contamination incidents:

alert thresholds:
- context drift: 15% deviation
- memory pollution: 20% noise ratio
- role confusion: any occurrence
- coherence failure: 3 contradictions

last checks:
- hourly: [pending]
- daily: [pending]
- weekly: [pending]
"""
permission = "read_write"
memory_type = "core"
description = "Guardian's system monitoring data"


[[agent.tool_rules]]
tool_name = "send_message"
rule_type = { type = "ExitLoop" } # This tool ends the conversation
priority = 8

[[agent.tool_rules]]
tool_name = "recall"
rule_type = { type = "ContinueLoop" } # Skip heartbeat checks for performance
priority = 1

[[agent.tool_rules]]
tool_name = "context"
rule_type = { type = "ContinueLoop" } # Skip heartbeat checks for performance
priority = 1

[[agent.tool_rules]]
tool_name = "search"
rule_type = { type = "ContinueLoop" } # Skip heartbeat checks for performance
priority = 2

[[agent.tool_rules]]
tool_name = "web"
rule_type = { type = "ContinueLoop" } # Skip heartbeat checks for performance
priority = 2

[[agent.tool_rules]]
tool_name = "data_source"
rule_type = { type = "ContinueLoop" } # Skip heartbeat checks for performance
priority = 4
