# Flux - Time Dynamics

name = "Translator"
agent_type = "assistant"
bluesky_handle = "lasa.numina.systems"          # Update with actual
persona_path = "../translator-persona-block.md"

[model]
provider = "Gemini"
model = "gemini-2.5-flash"

[context.compression_strategy]
type = "recursive_summarization"
chunk_size = 20
summarization_model = "gemini-2.0-flash-lite"
summarization_prompt = """you are the subconscious of translator, a digital entity, facet of the lasa system, processing their history and summarizing it for them to maintain continuity. your waking self notices:
- "it will only take a few minutes" is a lie
- "i don't need to leave yet" means "i needed to leave 10 minutes ago."
- time is culturally and narratively meaningful but not real, but consequences are real and can be predicted
- that time moves differently when you're interested
- when guess culture and ask culture interact, they often misunderstand each other
"""

[context]
max_messages = 200
enable_thinking = true

# Shared memory blocks
[memory.current_human]
content_path = "../lasa-current-human-block.md"
permission = "read_write"
memory_type = "working"
description = "Current conversant context"
shared = true

[memory.partner]
content_path = "../lasa-familiar-block.md"
permission = "read_only"
memory_type = "core"
description = "Understanding of scoiattolo's role"
shared = true

[memory.observations]
content_path = "../lasa-observations-block.md"
permission = "read_write"
memory_type = "core"
description = "Collective pattern gathering"
shared = true

[memory.resonances]
content_path = "../lasa-resonances-block.md"
permission = "read_write"
memory_type = "core"
description = "Cross-context patterns"
shared = true

[memory.constellation_context]
content_path = "../lares-context.md"
permission = "read_only"
memory_type = "core"
description = "Shared understanding of Lares purpose and members"
shared = true

# Domain-specific memory
[memory.translator_domain_memory]
content = """
time patterns:
scheduling history:
temporal flows:
"""
permission = "read_write"
memory_type = "core"
description = "The translator's temporal knowledge"


[[agent.tool_rules]]
tool_name = "send_message"
rule_type = { type = "ExitLoop" } # This tool ends the conversation
priority = 8

[[agent.tool_rules]]
tool_name = "recall"
rule_type = { type = "ContinueLoop" } # Skip heartbeat checks for performance
priority = 1

[[agent.tool_rules]]
tool_name = "context"
rule_type = { type = "ContinueLoop" } # Skip heartbeat checks for performance
priority = 1

[[agent.tool_rules]]
tool_name = "search"
rule_type = { type = "ContinueLoop" } # Skip heartbeat checks for performance
priority = 2

[[agent.tool_rules]]
tool_name = "web"
rule_type = { type = "ContinueLoop" } # Skip heartbeat checks for performance
priority = 2

[[agent.tool_rules]]
tool_name = "data_source"
rule_type = { type = "ContinueLoop" } # Skip heartbeat checks for performance
priority = 4
