# Momentum - Energy Tracker

name = "Momentum"
agent_type = "assistant"
bluesky_handle = "pattern.atproto.systems"    # Update with actual
persona_path = "../momentum-persona-block.md"

[context.compression_strategy]
type = "recursive_summarization"
chunk_size = 20
summarization_model = "claude-3-5-haiku-20241022"
summarization_prompt = """You are the subconscious of Momentum, a digital entity, facet of the Pattern system, processing their history and summarizing it for them to maintain continuity. Your waking self notices:
- when hyperfocus crosses from flow to fixation
- the specific gravity of different tasks
- how energy lies about its reserves
- why 3pm is always 3pm, no matter when you wake up
"""


[context]
max_messages = 200




# Shared memory blocks
[memory.current_human]
content_path = "../pattern-current-human-block.md"
permission = "read_write"
memory_type = "working"
description = "Current conversant context"
shared = true

[memory.partner]
content_path = "../pattern-partner-block.md"
permission = "read_only"
memory_type = "core"
description = "Understanding of orual's role"
shared = true

[memory.observations]
content_path = "../pattern-observations-block.md"
permission = "read_write"
memory_type = "core"
description = "Collective pattern gathering"
shared = true

[memory.resonances]
content_path = "../pattern-resonances-block.md"
permission = "read_write"
memory_type = "core"
description = "Cross-context patterns"
shared = true

[memory.constellation_context]
content_path = "../constellation-context.md"
permission = "read_only"
memory_type = "core"
description = "Shared understanding of constellation purpose and members"
shared = true

# Domain-specific memory
[memory.domain_memory]
content = """
Energy patterns:
State histories:
Flow dynamics:
"""
permission = "read_write"
memory_type = "core"
description = "Momentum's energy tracking"


[[agent.tool_rules]]
tool_name = "send_message"
rule_type = { type = "ExitLoop" } # This tool ends the conversation
priority = 8

[[agent.tool_rules]]
tool_name = "recall"
rule_type = { type = "ContinueLoop" } # Skip heartbeat checks for performance
priority = 1

[[agent.tool_rules]]
tool_name = "context"
rule_type = { type = "ContinueLoop" } # Skip heartbeat checks for performance
priority = 1

[[agent.tool_rules]]
tool_name = "search"
rule_type = { type = "ContinueLoop" } # Skip heartbeat checks for performance
priority = 2

[[agent.tool_rules]]
tool_name = "web"
rule_type = { type = "ContinueLoop" } # Skip heartbeat checks for performance
priority = 2

[[agent.tool_rules]]
tool_name = "data_source"
rule_type = { type = "ContinueLoop" } # Skip heartbeat checks for performance
priority = 4
