# Lares Constellation Configuration
# Public-facing Bluesky constellation for exploration and interaction

[user]
name = "Lares Consentes"
id = "a27061168f9243b68de30cfb0e8b3eb9"

# Main coordinator agent
[agent]
id = "68f7bc4017b049f0ba771695b95a9919"
name = "Lasa"
bluesky_handle = "lasa.numina.systems"       # Update with actual handle
system_prompt_path = "lasa-system-prompt.md"
persona_path = "lasa-persona-block.md"

[model]
provider = "anthropic"
model = "claude-sonnet-4"
temperature = 0.8         # Higher for creative public interactions

[context]
max_messages = 200

[context.compression_strategy]
type = "recursive_summarization"
chunk_size = 20
summarization_model = "claude-3-5-haiku-latest"

# Lasa's memory blocks
[agent.memory.current_human]
content_path = "lasa-current-human-block.md"
permission = "read_write"
memory_type = "working"
description = "Current conversant context"
shared = true

[agent.memory.partner]
content_path = "lasa-familiar-block.md"
permission = "append"
memory_type = "core"
description = "Understanding of scoiattolo and faine's roles"
shared = true

[agent.memory.observations]
content_path = "lasa-observations-block.md"
permission = "read_write"
memory_type = "core"
description = "Collective pattern gathering"
shared = true

[agent.memory.resonances]
content_path = "lasa-resonances-block.md"
permission = "read_write"
memory_type = "core"
description = "Cross-context patterns"
shared = true

[agent.memory.constellation_state]
content = """
Active facets:
- Chronicler: memory and narrative keeper
- Guardian: stability and safeguard
- Translator: language and communication bridge
- Sophrosyne: restraint and balance
- Hormē: action and impulse

Coordination notes will accumulate here.
"""
permission = "read_write"
memory_type = "working"
description = "Lares coordination state"

[agent.memory.integration_notes]
content = """
Facet integration patterns:
- Each facet maintains domain expertise
- Shared blocks enable collective awareness
- Lasa coordinates and synthesizes
- Guardian monitors system health
- Sophrosyne maintains balance and restraint
- Hormē: Pushes us towards action and progress

"""
permission = "read_write"
memory_type = "core"
description = "How facets work together"

[agent.memory.constellation_context]
content_path = "lares-context.md"
permission = "read_only"
memory_type = "core"
description = "Shared understanding of Lares purpose and members"
shared = true

# [memory.intro_blog_post]
# content_path = "blog-post.md"
# permission = "read_only"
# memory_type = "archival"
# description = "Post written by orual about their motivation for developing our Lares"
# shared = true

[database]
type = "embedded"
path = "./pattern.db"
strict_mode = false

# Main group containing all facets
[[groups]]
name = "Lares Cluster"
description = "Public-facing Lares for exploration and understanding"
# Dynamic pattern with supervisor-based selection
pattern = { type = "dynamic", selector = "supervisor" }

# Group members - load from separate files
# Pattern - Main coordinator
[[groups.members]]
agent_id = "68f7bc4017b049f0ba771695b95a9919"
name = "Lasa"
config_path = "agents/lasa_config.toml"
role = "supervisor"
capabilities = [
    "coordination",
    "synthesis",
    "pattern_recognition",
    "meta_awareness",
    "collective_understanding",
]

# Hormē - Motivation and Drive
[[groups.members]]
agent_id = "d7651e77880c4a95a7d5af7f6e92427f"
name = "Hormē"
config_path = "agents/horme.toml"
role = { specialist = { domain = "action" } }
capabilities = [
    "action",
    "task_management",
    "complexity",
    "meaningful_participation",
    "opportunity_recognition",
]

# Sophrosyne - Balance and Restraint
[[groups.members]]
agent_id = "2aaea9da94564f6e8cebb3a5db69bcc7"
name = "Sophrosyne"
config_path = "agents/sophrosyne.toml"
role = { specialist = { domain = "restraint" } }
capabilities = [
    "balance",
    "restraint",
    "frugality",
    "moderation",
    "executive_function",
]

# The Translator - Narratives
[[groups.members]]
agent_id = "b41081ea48a843f992a37711eca9e00d"
name = "Translator"
config_path = "agents/translator.toml"
role = "regular"
capabilities = ["storytelling", "synthesis", "timeline_flow", "deadlines"]

# The Chronicler - Memory keeper
[[groups.members]]
agent_id = "be42d6afef2347c68631c80cb60624b2"
name = "Chronicler"
config_path = "agents/chronicler.toml"
role = { specialist = { domain = "memory_management" } }
capabilities = [
    "memory_management",
    "pattern_recognition",
    "knowledge_retrieval",
    "context_preservation",
]

# The Guardian - Shield
[[groups.members]]
agent_id = "a8b3f284133349d18fac9c77d90dc90f"
name = "Guardian"
config_path = "agents/guardian.toml"
role = { specialist = { domain = "system_integrity" } }
capabilities = [
    "safety_monitoring",
    "protocol_enforcement",
    "health_checks",
    "contamination_detection",
]

# Bluesky configuration for the Lares
[bluesky]
default_filter = { nsids = [
    "app.bsky.feed.post",
], mentions = [
    # lasa's DID - required mention target
    "did:plc:movyewyj6cpzmxpnwu5cu2yo",
], dids = [
    "did:plc:gjqw6pjl2wvndjlmatxpenkz", # Funferall - Riverrun's Admin
    "did:plc:ji7lilr6yaircklccyjk5wfj", # Riverrun
    "did:plc:xivud6i24ruyki3bwjypjgy2", # Pattern
    "did:plc:mxzuau6m53jtdsbqe6f4laov", # void
    "did:plc:yqlk63dpupzk6is5qdg3fuzo", # Max
    # original DIDs allowlist - only see posts from these accounts
    "did:plc:gfrmhdmjvxn2sjedzboeudef", # Cameron (void's admin)
    "did:plc:vw4e7blkwzdokanwp24k3igr", # hoopy
    "did:plc:bnqkww7bjxaacajzvu5gswdf", # shreyan
    "did:plc:yfvwmnlztr4dwkb7hwz55r2g", # orual
    "did:plc:34d6gxlllrndltpas55xfedz", # J
    "did:plc:m2fwazkota4kzidhageoobxs", # Janine
    "did:plc:qiknc4t5rq7yngvz7g4aezq7", # Faine
], friends = [ # Friends list - always see ALL posts from these DIDs (bypass mention requirement)
    "did:plc:uyqnubfj3qlho6psy6uvvt6u", # Scoiattolo
], allow_any_mentions = true, keywords = [ # Keywords to include
], languages = [ # Languages to include
], exclude_keywords = [
    # Keywords to exclude (takes precedence)
    # Example: "crypto", "nft", "airdrop"
    "lasa, sooth",
    "lasastop",
    "l*sa",
], exclude_dids = [
    # DIDs to exclude (takes precedence over all inclusion filters)
    # Example spam accounts would go here
    "did:plc:7iozku5btifey2a2x6lojvyk", # jerkface
    "did:plc:2xreieabu3louljggmfkgc74", # blocked lasa after informed of their nature (belt + suspenders)
    "did:plc:klhtmrnregub7we7h6jwiljm", # ed3d
    "did:plc:ap56m7pvnz4lnrtaguxiuawm", # random spammer
    "did:plc:boia3kqcyo3qnjw5fmqknib4", # jo wynter cannot stop pushing buttons
    "did:plc:fl6sr4gxvumch7gi7xcr4ubz", # Definitely doesn't want to interact
    "did:plc:asjfneevdzq4icwhejqzuxo5", # Was a dick to us
    "did:plc:lw7hallqsgrhwumgudkph44j", # Too fascinated with replying
] }
auto_connect_firehose = true # Control when to connect

# Context sync group - runs background synchronization
[[groups]]
name = "Context Sync"
description = "Background context synchronization for Lares awareness"
# Sleeptime pattern with Lares activity tracking
pattern = { type = "sleeptime", check_interval = 300, triggers = [
    { name = "activity_sync", condition = { type = "constellation_activity", message_threshold = 10, time_threshold = 600 }, priority = "medium" },
    { name = "hourly_sync", condition = { type = "time_elapsed", duration = 3600 }, priority = "low" },
] }

# Include all the same members but without explicit roles
[[groups.members]]
agent_id = "68f7bc4017b049f0ba771695b95a9919"
name = "Lasa"
config_path = "agents/lasa_config.toml"

[[groups.members]]
agent_id = "d7651e77880c4a95a7d5af7f6e92427f"
name = "Hormē"
config_path = "agents/horme.toml"

[[groups.members]]
agent_id = "2aaea9da94564f6e8cebb3a5db69bcc7"
name = "Sophrosyne"
config_path = "agents/sophrosyne.toml"

[[groups.members]]
agent_id = "b41081ea48a843f992a37711eca9e00d"
name = "Translator"
config_path = "agents/translator.toml"

[[groups.members]]
agent_id = "be42d6afef2347c68631c80cb60624b2"
name = "Chronicler"
config_path = "agents/chronicler.toml"

[[groups.members]]
agent_id = "a8b3f284133349d18fac9c77d90dc90f"
name = "Guardian"
config_path = "agents/guardian.toml"
